# Welcome to serverless. Read the docs
# https://serverless.com/framework/docs/

# Serverless.yml is the configuration the CLI
# uses to deploy your code to your provider of choice

# The `service` block is the name of the service
service: auth0-authentication

# The `provider` block defines where your service will be deployed
provider:
  name: aws
  runtime: nodejs6.10
  memorySize: 128
  stage: dev
  profile: serverless
  environment: ${file(env-${self:custom.stage}.yml)} # environment settings in env-*.yml files

plugins:
  - serverless-offline

custom:
  stage: "${opt:stage, self:provider.stage}"

# The `functions` block defines what code to deploy
functions:
  auth0Authentication:
    handler: handler.auth0Authentication
    # The `events` block defines how to trigger the handler.auth0Authentication code
    events:
      - http:
          path: authenticate
          method: post
          cors: true
